### ISSUE TITLE
Typo in MathEngine_Tutorial notebook

### ISSUE THREAD

**Issue by kwerner0** [LORD-MicroStrain/SensorCloud#2]
SensorCloud/MathEngine/Example Notebooks/MathEngine_Tutorial.ipynb

Highlighted below should be changed to .getTimeStamps()

![image](https://cloud.githubusercontent.com/assets/12631157/7844378/f86fdb62-047d-11e5-83f7-25f2e26de45c.png)

**Comment by rwslord** [comment]
fixed in f810a59ce5216ca5437793157a349e68805112ac
