### ISSUE TITLE
Does it support XML and JSON data format for requests?

### ISSUE THREAD

**Issue by DevasenaInupakutika** [LORD-MicroStrain/SensorCloud#3]
Hi, 

As per the README, could you please let me know if support for xml and json data formats for some of the requests has been added? 

I could see in API for xml format. For what kind of requests this support has been added?

**Comment by brblord** [comment]
Hello, currently we have not released additional XML/JSON support for the API beyond what is documented.  We've found the XDR format to be the most efficient for sending large data chunks, so have promoted its use.  We do still intend to add further JSON support in the future, but these requests will likely be more limited in data quantity than the current XDR formats.

**Comment by DevasenaInupakutika** [comment]
Ok. Thank you!
